name: "First PR greeter"
on: [pull_request]

jobs:
  pr-greeter:
    runs-on: ubuntu-latest
    steps:
      - name: Greet first PR
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            ## Hurray!
            Looks like this is your first PRğŸ‘
            Thanks for contributing and welcome to the community ğŸ‰
